databases:
  ###############################################################
  # to sync db migrations
  ###############################################################
  - name: rad-postgres
    databaseName: rad
    plan: pro

services:
  ###############################################################
  # RAD! app frontend and backend
  ###############################################################
  - type: web
    name: rad-frontend
    env: node
    plan: starter
    buildCommand: yarn; yarn build
    startCommand: yarn start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: rad-backend
          property: hostport
  - type: web
    name: rad-backend
    runtime: docker
    repo: https://github.com/ragathon-care/rad.git
    region: oregon
    plan: standard
    rootDir: ./backend
    # https://render.com/docs/blueprint-spec#scaling
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 75 # optional if targetCPUPercent is set (valid: 1-90)
      targetCPUPercent: 75 # optional if targetMemory is set (valid: 1-90)
    healthCheckPath: /api/health/
    initialDeployHook: make seed_db_based_on_env
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rad-postgres
          property: connectionString
      - fromGroup: general-settings
      - fromGroup: prod-web-secrets

  ###############################################################
  # Object store and console for quick review
  ###############################################################
  - type: web
    name: objectstore
    healthCheckPath: /minio/health/live
    runtime: image
    image:
      url: docker.io/minio/minio:RELEASE.2023-08-04T17-40-21Z.hotfix.04968f7ec
    dockerCommand: minio server /data
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: MINIO_ROOT_USER
        generateValue: true
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: MINIO_BROWSER
        value: "off"
  - type: web
    name: objectstore-console
    runtime: image
    image:
      url: minio/console:v0.30.0
    dockerCommand: /bin/bash -c CONSOLE_MINIO_SERVER=https://$MINIO_HOST.onrender.com ./console server --port $PORT
    autoDeploy: false
    envVars:
      - key: CONSOLE_PBKDF_PASSPHRASE
        generateValue: true
      - key: CONSOLE_PBKDF_SALT
        generateValue: true
      - key: PORT
        value: 9090
      - key: MINIO_HOST
        fromService:
          name: objectstore
          type: web
          property: host
  
  ###############################################################
  # to sync db migrations
  ###############################################################
  - type: cron
    name: rad-cron
    runtime: docker
    repo: https://github.com/ragathon-care/rad.git
    region: oregon
    plan: standard
    rootDir: ./backend
    # set to the fake date of Feb 31st so it never runs. Meant to be manually triggered.
    schedule: "0 5 31 2 ?"
    dockerCommand: make seed_db_based_on_env
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rad-postgres
          property: connectionString
      - fromGroup: general-settings
      - fromGroup: prod-web-secrets


envVarGroups:
- name: general-settings
  envVars:
    - key: IS_PREVIEW_ENV
      value: false
    - key: LOG_LEVEL
      value: INFO
    - key: BACKEND_CORS_ORIGINS
      value: '["http://localhost", "http://localhost:8000", "http://localhost:3000", "http://127.0.0.1:3000", "https://rad-backend.onrender.com", "https://rad-frontend.onrender.com", "http://secinsights.ai", "http://www.secinsights.ai", "https://secinsights.ai", "https://www.secinsights.ai"]'
    # S3_BUCKET_NAME is the bucket used for the StorageContext of the backend's LlamaIndex chat engine
    - key: S3_BUCKET_NAME
      value: rad-objects
    # S3_ASSET_BUCKET_NAME is the bucket used for app assets (e.g. document PDFs)
    - key: S3_ASSET_BUCKET_NAME
      value: rad-web-assets-prod
    - key: CDN_BASE_URL
      value: https://d687lz8k56fia.cloudfront.net
    - key: SENTRY_DSN
      sync: false
- name: prod-web-secrets
  envVars:
    # Manually add a prod value for OPENAI_API_KEY in Render dashboard
    - key: OPENAI_API_KEY
      sync: false
    - key: AWS_KEY
      sync: false
    - key: AWS_SECRET
      sync: false
    - key: POLYGON_IO_API_KEY
      sync: false
    - key: VECTARA_API_KEY
      sync: false
    - key: VECTARA_CORPUS_ID
      sync: false
    - key: VECTARA_CUSTOMER_ID
      sync: false
    - key: DIFFBOT_API_KEY
      sync: false
