version: '3'
services:
  rad-backend:
    build:
      context: .
    volumes:
      # allows for live reloading of the app
      # when the code within the ./app directory changes
      - ./:/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker
    environment:
      BACKEND_CORS_ORIGINS: '["http://localhost", "http://localhost:8000"]'

  db:
    image: ankane/pgvector:v0.5.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rad
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
